### ISSUE TITLE
m_cost docs

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [thibaultcha/lua-argon2#25]
https://github.com/P-H-C/phc-winner-argon2 states:
```
-m N            Sets the memory usage of 2^N KiB (default 12)
```
while your doc states that m_cost N === N KiB. It's a huge difference, in particular m_cost=24 used in your examples should require 16 GiB of memory

**Comment by thibaultcha** [comment]
Feel free to send a PR.

**Comment by thibaultcha** [comment]
Thanks for the report, I just pushed some improvements to the documentation. They won't be put online to the docs website until version 3.x of this module is released though (due to recent breaking changes).

**Comment by thibaultcha** [comment]
Actually, this was a mistake and the documentation was correct. Only the Argon2 CLI is `2^N KiB`.

**Comment by Bulat-Ziganshin** [comment]
i'm sorry :(
