### ISSUE TITLE
ANSI C can't alloc dynamic arrays on the stack

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [thibaultcha/lua-argon2#26]
i see that you alloc space directly in the stack in https://github.com/thibaultcha/lua-argon2/blob/master/src/argon2.c#L288

i think this technique isn't a standard C, probably just a GNU extension. Instead, you can build arbitrary-length string with luaL_buffinitsize+luaL_pushresultsize

**Comment by thibaultcha** [comment]
Thanks for the suggestion! PRs welcomed.

**Comment by thibaultcha** [comment]
I have just created #27 to address this. Feel free to leave a review there :)

**Comment by thibaultcha** [comment]
(I don't think this use case fits that of what `luaL_Buffer` was designed for, so I went with using a plain `malloc`.)

**Comment by Bulat-Ziganshin** [comment]
Example of using buffer API to build the string: https://www.lua.org/source/5.2/lstrlib.c.html#str_reverse

I don't know, though, whether it was supported by earlier Lua versions. It should be faster than malloc-based solution (which is unimportant here :) ) and more "clean" - i.e. don't use dynamic memory when Lua itself, f.e., called with some other memory allocation routines

**Comment by thibaultcha** [comment]
This code is specific to Lua 5.2 but I just pushed e9c5d95cd754e8aa0bd85bc2086ab26f8400f242 which uses a `luaL_Buffer` and stayc compatible with Lua 5.1/LuaJIT.

**Comment by thibaultcha** [comment]
I just pushed version 3.0.0 of this module to Luarocks: http://luarocks.org/modules/thibaultcha/argon2 

This version also introduces a Changelog file if you are curious.

Thanks for your feedback!
