### ISSUE TITLE
Salt is truncated by hash_encoded

### ISSUE THREAD

**Issue by jmthackett** [thibaultcha/lua-argon2#36]
Hey! I've just started using this library and I'm having a little trouble. My aim is to take a hash created by a php application and verify a user has entered the correct password. I have a little logic which pulls out the salt so I can use the `hash_encoded` function.

The problem I have found is that while `hash_encoded` expects a non-base64 encoded salt, the way it encodes the salt appears to truncate it by 2 characters or so. Salt chosen "randomly" for example purposes, but this is recreatable with pretty much all input as far as I can see, including those from hashes encoded by PHP's crypt() functions. See my test case below:

```
local argon2 = require "argon2"
local mime = require "mime"
test = "55555555555555555555555555555555ABCDEF=="
compare = assert(argon2.hash_encoded('nothing-to-see-here', (mime.unb64(test)), { -- extra brackets to throw away all but the first return value, according to the mime docs
  t_cost = 4, 
  m_cost = 65536, 
  parallelism = 1, 
  hash_len = 32 
})) 

print(test) 
print((mime.unb64(test))) 
print((mime.unb64((mime.b64(test))))) 
print(compare) 
```

Results:

```
$ lua test.lua
55555555555555555555555555555555ABCDEF==
yyyyyyyy
55555555555555555555555555555555ABCDEF==
$argon2i$v=19$m=65536,t=4,p=1$55555555555555555555555555555555ABCDEA$quWqC6VIqSrWqnm5em6MnV7gHvBIf8pwXDUVk2bzFJ0
```
Lines 1 and 3 match, which is expected. But observe the same string in the final line: the latter part reads `ABCDEA` instead of `ABCDEF`. This means that verifying the password will always fail. 

Is it something I'm doing?

**Comment by thibaultcha** [comment]
Hi,

Using the `verify` API on your example seems to work just fine:

```lua
local ok, err = argon2.verify(compare, "nothing-to-see-here")
print(ok) -- true
```

**Comment by jmthackett** [comment]
Hey,

Sorry about this, I think I went wrong in a few ways.

a) I didn't realise that `''` in lua wasn't as literal as `[[]]` and had a password I was trying to verify with backslashes in it. I'm a little new to lua, lesson learned.
b) I had been trying to produce the same string output as php's `password_hash`, which appears to not work like I assumed it would, but appears to not actually actually be a requirement.

Having worked out the above I'm now successfully verifying a password.

Sorry to have bugged you, and many many thanks for the great library.

**Comment by thibaultcha** [comment]
No worries! I noticed that the non-b64 password string had some strange bytes in it, but the Argon2 specifications as well as the Lua 5.x manual both explicitly mention that they support NULL bytes, so even if you do have such passwords to hash, you should be covered :)
Maybe we could add some tests for such strings. Also, don't hesitate to look at the tests for more insights on how to use this library.
